defmodule Sorteios.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:rifas), :user_id, to: :owener_id

    drop constraint(:rifas, "rifas_user_id_fkey")

    alter table(:rifas) do
      modify :owener_id,
             references(:users,
               column: :id,
               name: "rifas_owener_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:rifas, "rifas_owener_id_fkey")

    alter table(:rifas) do
      modify :owener_id,
             references(:users,
               column: :id,
               name: "rifas_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:rifas), :owener_id, to: :user_id
  end
end
