defmodule Sorteios.Repo.Migrations.MigrateResources8 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rifas) do
      add :user_id,
          references(:users,
            column: :id,
            name: "rifas_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:rifas, "rifas_user_id_fkey")

    alter table(:rifas) do
      remove :user_id
    end
  end
end
