defmodule Sorteios.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:rifas, "rifas_user_id_fkey")

    alter table(:rifas) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "rifas_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nothing
             )
    end
  end

  def down do
    drop constraint(:rifas, "rifas_user_id_fkey")

    alter table(:rifas) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "rifas_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
