defmodule Sorteios.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tickets, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "tickets_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :rifa_id,
          references(:rifas,
            column: :id,
            name: "tickets_rifa_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:tickets, "tickets_user_id_fkey")

    drop constraint(:tickets, "tickets_rifa_id_fkey")

    drop table(:tickets)
  end
end
