defmodule Sorteios.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:rifas) do
      add :owner_id,
          references(:users,
            column: :id,
            name: "rifas_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:rifas, "rifas_owner_id_fkey")

    alter table(:rifas) do
      remove :owner_id
    end
  end
end
